CREATE TABLE customers(
	id CHAR(36)  PRIMARY KEY,
	full_name VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	category ENUM ("VIP","REGULAR","NEW") NOT NULL,
	notes TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE appointments(
	id CHAR(36) PRIMARY KEY,
	customer_id CHAR(36) NOT NULL,
	title VARCHAR(40) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	appointment_date DATETIME,
	location VARCHAR(50),
	STATUS ENUM("PENDING","DONE","CANCELLED") DEFAULT "PENDING",
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (customer_id) REFERENCES customers(id)
);