CREATE TABLE tasks(
	id CHAR(36) PRIMARY KEY,
	customer_id CHAR(36) NOT NULL,
	title VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	STATUS ENUM("PENDING","DONE","CANCELLED") DEFAULT "PENDING",
	due_date DATETIME,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE communications(
	id CHAR(36) PRIMARY KEY,
	customer_id CHAR(36) NOT NULL,
	title VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	STATUS ENUM("EMAIL","CALL","MEETING"),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (customer_id) REFERENCES customers(id)
);